// var anions = {
//     Cl   : [{name: "Cl",    element: ["Cl"], charge: -1, mfH: -167.1508, mfS: 56.484, mfG: -131.25208}],
//     ClO  : [{name: "ClO",   element: ["Cl", "O"], charge: -1, mfH: -107.1104, mfS: 41.84, mfG: -36.8192}],
//     ClO2 : [{name: "ClO2",  element: ["Cl", "O"], charge: -1, mfH: -66.5256, mfS: 101.2528, mfG: 17.1544}],
//     ClO3 : [{name: "ClO3",  element: ["Cl", "O"], charge: -1, mfH: -99.1608, mfS: 162.3392, mfG: -3.3472}],
//     ClO4 : [{name: "ClO4",  element: ["Cl", "O"], charge: -1, mfH: -129.32744, mfS: 182.004, mfG: -8.61904}],
//     CO3  : [{name: "CO3",   element: ["C", "O"], charge: -2, mfH: -677.13856, mfS: -56.9024, mfG: -527.89528}],
//     HCO3 : [{name: "HCO3",  element: ["H", "C", "O"], charge: -1, mfH: -691.99176, mfS: 91.2112, mfG: -586.84784}],
//     CN   : [{name: "CN",    element: ["C", "N"], charge: -1, mfH: 150.624, mfS: 94.14, mfG: 172.3808}],
//     Cr2O7: [{name: "Cr2O7", element: ["Cr", "O"], charge: -2, mfH: -1490.3408, mfS: 261.9184, mfG: -1301.224}],
//     CrO4 : [{name: "CrO4",  element: ["Cr", "O"], charge: -2, mfH: -881.1504, mfS: 50.208, mfG: -727.84864}],
//     F    : [{name: "F",     element: ["F"], charge: -1, mfH: -255.6424, mfS: 145.47768, mfG: -262.3368}],
//     S    : [{name: "S",     element: ["S"], charge: -2, mfH: 145.47768, mfS: -14.644, mfG: 85.772}],
//     HS   : [{name: "HS",    element: ["H", "S"], charge: -1, mfH: -17.5728, mfS: 62.76, mfG: 12.04992}],
//     SO3  : [{name: "SO3",   element: ["S", "O"], charge: -2, mfH: -635.5496, mfS: -29.288, mfG: -486.5992}],
//     HSO3 : [{name: "HSO3",  element: ["H", "S", "O"], charge: -1, mfH: -626.21928, mfS: 139.7456, mfG: -527.8116}],
//     SO4  : [{name: "SO4",   element: ["S", "O"], charge: -2, mfH: -909.26688, mfS: 20.0832, mfG: -744.62648}],
//     HSO4 : [{name: "HSO4",  element: ["H", "S", "O"], charge: -1, mfH: -886.3, mfS: 131.8, mfG: -755.9}], //
//     NO3  : [{name: "NO3",   element: ["N", "O"], charge: -1, mfH: -207.35904, mfS: 146.44, mfG: -111.33624}],
//     OH   : [{name: "OH",    element: ["O", "H"], charge: -1, mfH: -229.99448 , mfS: -10.75288, mfG: -157.27656}],
//     MnO4 : [{name: "MnO4",  element: ["Mn", "O"], charge: -1, mfH: -541.4096, mfS: 191.2088, mfG: -447.2696}, {name: "MnO4", element: ["Mn", "O"], charge: -2, mfH: -652.704, mfS: 58.576, mfG: -500.8248}],
//     PO4  : [{name: "PO4",   element: ["P", "O"], charge: -3, mfH: -1277.3752, mfS: -221.752, mfG: -1018.804}],
//     HPO4 : [{name: "HPO4",  element: ["H", "P", "O"], charge: -2, mfH: -1292.14472, mfS: -33.472, mfG: -1089.26256}],
//     H2PO4: [{name: "H2PO4", element: ["H", "P", "O"], charge: -1, mfH: -1296.28688, mfS: 90.3744, mfG: -1130.39128}],
//     I    : [{name: "I",     element: ["I"], charge: -1, mfH: 175.05856, mfS: 245.3916, mfG: -51.58872}],
//     IO   : [{name: "IO",    element: ["I", "O"], charge: -1, mfH: -107.5288, mfS: -5.4392, mfG: -38.4928}],
//     IO3  : [{name: "IO3",   element: ["I", "O"], charge: -1, mfH: -221.3336, mfS: 118.4072, mfG: -128.0304}],

//     CH3COO : [{name: "CH3COO", element: ["C", "H", "O"], charge: -1, mfH: -468.0, mfS: 86.6,  mfG: -369.3}],
// };
// var cations = {
//     H  : [{name: "H",   element: ["H"], charge: +1, mfH: 0, mfS: 0, mfG: 0}],
//     NH4: [{name: "NH4", element: ["H", "N"], charge: +1, mfH: -132.50728, mfS: -132.50728, mfG: -79.37048}],
//     Fe : [{name: "Fe",  element: ["Fe"], charge: +2, mfH: -89.1192, mfS: -137.6536, mfG: -78.8684}, {name: "Fe", charge: +3, mfH: -48.5344, mfS: -315.892, mfG: -4.6024}],
//     Mn : [{name: "Mn",  element: ["Mn"], charge: +2, mfH: -220.83152, mfS: -73.6384, mfG: -228.028}],
//     Mg : [{name: "Mg",  element: ["Mg"], charge: +2, mfH: -466.85072, mfS: -138.072, mfG: -454.8008}],
//     Zn : [{name: "Zn",  element: ["Zn"], charge: +2, mfH: -153.9, mfS: -112.1, mfG: -147.1}], //
//     Ca : [{name: "Ca",  element: ["Ca"], charge: +2, mfH: -542.8, mfS: -53.1, mfG: -553.6}], //
//     Na : [{name: "Na",  element: ["Na"], charge: +1, mfH: undefined, mfS: undefined, mfG: undefined}], // 
//     K  : [{name: "K",   element: ["K"], charge: +1, mfH: undefined, mfS: undefined, mfG: undefined}], //
//     Cu : [{name: "Cu",  element: ["Cu"], charge: +2, mfH: 64.76832, mfS: -99.5792, mfG: 65.52144}], //
//     Pb : [{name: "Pb",  element: ["Pb"], charge: +2, mfH: undefined, mfS: undefined, mfG: undefined}], //
//     Ba : [{name: "Ba",  element: ["Ba"], charge: +2, mfH: -537.644, mfS: 9.6232, mfG: -560.73968}], //
//     Hg : [{name: "Hg",  element: ["Hg"], charge: +2, mfH: undefined, mfS: undefined, mfG: undefined}], //
//     Cd : [{name: "Cd",  element: ["Cd"], charge: +2, mfH: undefined, mfS: undefined, mfG: undefined}], //
//     Tl : [{name: "Tl",  element: ["Tl"], charge: +1, mfH: undefined, mfS: undefined, mfG: undefined}], //

// };
// var substance = [
//     {name: "(NH4)2CO3", cation: [["NH4", 2]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "(NH4)2Cr2O7", cation: [["NH4", 2]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "(NH4)2CrO4", cation: [["NH4", 2]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "(NH4)2HPO4", cation: [["NH4", 2]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "(NH4)2MnO4", cation: [["NH4", 2]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "(NH4)2S", cation: [["NH4", 2]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "(NH4)2SO3", cation: [["NH4", 2]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "(NH4)2SO4", cation: [["NH4", 2]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "(NH4)3PO4", cation: [["NH4", 3]], anion: [["PO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(CH3COO)2", cation: [["Ba", 1]], anion: [["CH3COO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(CN)2", cation: [["Ba", 1]], anion: [["CN", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(ClO)2", cation: [["Ba", 1]], anion: [["ClO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(ClO2)2", cation: [["Ba", 1]], anion: [["ClO2", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(ClO3)2", cation: [["Ba", 1]], anion: [["ClO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(ClO4)2", cation: [["Ba", 1]], anion: [["ClO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(H2PO4)2", cation: [["Ba", 1]], anion: [["H2PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(HCO3)2", cation: [["Ba", 1]], anion: [["HCO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(HS)2", cation: [["Ba", 1]], anion: [["HS", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(HSO3)2", cation: [["Ba", 1]], anion: [["HSO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(HSO4)2", cation: [["Ba", 1]], anion: [["HSO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(IO)2", cation: [["Ba", 1]], anion: [["IO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(IO3)2", cation: [["Ba", 1]], anion: [["IO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(MnO4)2", cation: [["Ba", 1]], anion: [["MnO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(NO3)2", cation: [["Ba", 1]], anion: [["NO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba(OH)2", cation: [["Ba", 1]], anion: [["OH", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ba3(PO4)2", cation: [["Ba", 3]], anion: [["PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "BaCO3", cation: [["Ba", 1]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "BaCl2", cation: [["Ba", 1]], anion: [["Cl", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "BaCr2O7", cation: [["Ba", 1]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "BaCrO4", cation: [["Ba", 1]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "BaF2", cation: [["Ba", 1]], anion: [["F", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "BaHPO4", cation: [["Ba", 1]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "BaI2", cation: [["Ba", 1]], anion: [["I", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "BaMnO4", cation: [["Ba", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "BaS", cation: [["Ba", 1]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "BaSO3", cation: [["Ba", 1]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "BaSO4", cation: [["Ba", 1]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(CH3COO)2", cation: [["Ca", 1]], anion: [["CH3COO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(CN)2", cation: [["Ca", 1]], anion: [["CN", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(ClO)2", cation: [["Ca", 1]], anion: [["ClO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(ClO2)2", cation: [["Ca", 1]], anion: [["ClO2", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(ClO3)2", cation: [["Ca", 1]], anion: [["ClO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(ClO4)2", cation: [["Ca", 1]], anion: [["ClO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(H2PO4)2", cation: [["Ca", 1]], anion: [["H2PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(HCO3)2", cation: [["Ca", 1]], anion: [["HCO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(HS)2", cation: [["Ca", 1]], anion: [["HS", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(HSO3)2", cation: [["Ca", 1]], anion: [["HSO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(HSO4)2", cation: [["Ca", 1]], anion: [["HSO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(IO)2", cation: [["Ca", 1]], anion: [["IO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(IO3)2", cation: [["Ca", 1]], anion: [["IO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(MnO4)2", cation: [["Ca", 1]], anion: [["MnO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(NO3)2", cation: [["Ca", 1]], anion: [["NO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca(OH)2", cation: [["Ca", 1]], anion: [["OH", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Ca3(PO4)2", cation: [["Ca", 3]], anion: [["PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CaCO3", cation: [["Ca", 1]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CaCl2", cation: [["Ca", 1]], anion: [["Cl", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CaCr2O7", cation: [["Ca", 1]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CaCrO4", cation: [["Ca", 1]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CaF2", cation: [["Ca", 1]], anion: [["F", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CaHPO4", cation: [["Ca", 1]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CaI2", cation: [["Ca", 1]], anion: [["I", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CaMnO4", cation: [["Ca", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CaS", cation: [["Ca", 1]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CaSO3", cation: [["Ca", 1]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CaSO4", cation: [["Ca", 1]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(CH3COO)2", cation: [["Cd", 1]], anion: [["CH3COO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(CN)2", cation: [["Cd", 1]], anion: [["CN", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(ClO)2", cation: [["Cd", 1]], anion: [["ClO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(ClO2)2", cation: [["Cd", 1]], anion: [["ClO2", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(ClO3)2", cation: [["Cd", 1]], anion: [["ClO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(ClO4)2", cation: [["Cd", 1]], anion: [["ClO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(H2PO4)2", cation: [["Cd", 1]], anion: [["H2PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(HCO3)2", cation: [["Cd", 1]], anion: [["HCO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(HS)2", cation: [["Cd", 1]], anion: [["HS", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(HSO3)2", cation: [["Cd", 1]], anion: [["HSO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(HSO4)2", cation: [["Cd", 1]], anion: [["HSO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(IO)2", cation: [["Cd", 1]], anion: [["IO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(IO3)2", cation: [["Cd", 1]], anion: [["IO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(MnO4)2", cation: [["Cd", 1]], anion: [["MnO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(NO3)2", cation: [["Cd", 1]], anion: [["NO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd(OH)2", cation: [["Cd", 1]], anion: [["OH", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cd3(PO4)2", cation: [["Cd", 3]], anion: [["PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CdCO3", cation: [["Cd", 1]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CdCl2", cation: [["Cd", 1]], anion: [["Cl", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CdCr2O7", cation: [["Cd", 1]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CdCrO4", cation: [["Cd", 1]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CdF2", cation: [["Cd", 1]], anion: [["F", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CdHPO4", cation: [["Cd", 1]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CdI2", cation: [["Cd", 1]], anion: [["I", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CdMnO4", cation: [["Cd", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CdS", cation: [["Cd", 1]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CdSO3", cation: [["Cd", 1]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CdSO4", cation: [["Cd", 1]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(CH3COO)2", cation: [["Cu", 1]], anion: [["CH3COO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(CN)2", cation: [["Cu", 1]], anion: [["CN", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(ClO)2", cation: [["Cu", 1]], anion: [["ClO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(ClO2)2", cation: [["Cu", 1]], anion: [["ClO2", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(ClO3)2", cation: [["Cu", 1]], anion: [["ClO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(ClO4)2", cation: [["Cu", 1]], anion: [["ClO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(H2PO4)2", cation: [["Cu", 1]], anion: [["H2PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(HCO3)2", cation: [["Cu", 1]], anion: [["HCO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(HS)2", cation: [["Cu", 1]], anion: [["HS", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(HSO3)2", cation: [["Cu", 1]], anion: [["HSO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(HSO4)2", cation: [["Cu", 1]], anion: [["HSO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(IO)2", cation: [["Cu", 1]], anion: [["IO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(IO3)2", cation: [["Cu", 1]], anion: [["IO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(MnO4)2", cation: [["Cu", 1]], anion: [["MnO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(NO3)2", cation: [["Cu", 1]], anion: [["NO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu(OH)2", cation: [["Cu", 1]], anion: [["OH", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Cu3(PO4)2", cation: [["Cu", 3]], anion: [["PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CuCO3", cation: [["Cu", 1]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CuCl2", cation: [["Cu", 1]], anion: [["Cl", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CuCr2O7", cation: [["Cu", 1]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CuCrO4", cation: [["Cu", 1]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CuF2", cation: [["Cu", 1]], anion: [["F", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CuHPO4", cation: [["Cu", 1]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CuI2", cation: [["Cu", 1]], anion: [["I", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CuMnO4", cation: [["Cu", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CuS", cation: [["Cu", 1]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CuSO3", cation: [["Cu", 1]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "CuSO4", cation: [["Cu", 1]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(CH3COO)2", cation: [["Fe", 1]], anion: [["CH3COO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(CH3COO)3", cation: [["Fe", 1]], anion: [["CH3COO", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(CN)2", cation: [["Fe", 1]], anion: [["CN", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(CN)3", cation: [["Fe", 1]], anion: [["CN", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(ClO)2", cation: [["Fe", 1]], anion: [["ClO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(ClO)3", cation: [["Fe", 1]], anion: [["ClO", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(ClO2)2", cation: [["Fe", 1]], anion: [["ClO2", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(ClO2)3", cation: [["Fe", 1]], anion: [["ClO2", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(ClO3)2", cation: [["Fe", 1]], anion: [["ClO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(ClO3)3", cation: [["Fe", 1]], anion: [["ClO3", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(ClO4)2", cation: [["Fe", 1]], anion: [["ClO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(ClO4)3", cation: [["Fe", 1]], anion: [["ClO4", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(H2PO4)2", cation: [["Fe", 1]], anion: [["H2PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(H2PO4)3", cation: [["Fe", 1]], anion: [["H2PO4", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(HCO3)2", cation: [["Fe", 1]], anion: [["HCO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(HCO3)3", cation: [["Fe", 1]], anion: [["HCO3", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(HS)2", cation: [["Fe", 1]], anion: [["HS", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(HS)3", cation: [["Fe", 1]], anion: [["HS", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(HSO3)2", cation: [["Fe", 1]], anion: [["HSO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(HSO3)3", cation: [["Fe", 1]], anion: [["HSO3", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(HSO4)2", cation: [["Fe", 1]], anion: [["HSO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(HSO4)3", cation: [["Fe", 1]], anion: [["HSO4", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(IO)2", cation: [["Fe", 1]], anion: [["IO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(IO)3", cation: [["Fe", 1]], anion: [["IO", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(IO3)2", cation: [["Fe", 1]], anion: [["IO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(IO3)3", cation: [["Fe", 1]], anion: [["IO3", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(MnO4)2", cation: [["Fe", 1]], anion: [["MnO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(MnO4)3", cation: [["Fe", 1]], anion: [["MnO4", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(NO3)2", cation: [["Fe", 1]], anion: [["NO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(NO3)3", cation: [["Fe", 1]], anion: [["NO3", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(OH)2", cation: [["Fe", 1]], anion: [["OH", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe(OH)3", cation: [["Fe", 1]], anion: [["OH", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe2(CO3)3", cation: [["Fe", 2]], anion: [["CO3", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe2(Cr2O7)3", cation: [["Fe", 2]], anion: [["Cr2O7", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe2(CrO4)3", cation: [["Fe", 2]], anion: [["CrO4", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe2(HPO4)3", cation: [["Fe", 2]], anion: [["HPO4", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe2(MnO4)3", cation: [["Fe", 2]], anion: [["MnO4", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe2(SO3)3", cation: [["Fe", 2]], anion: [["SO3", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe2(SO4)3", cation: [["Fe", 2]], anion: [["SO4", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe2S3", cation: [["Fe", 2]], anion: [["S", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Fe3(PO4)2", cation: [["Fe", 3]], anion: [["PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeCO3", cation: [["Fe", 1]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeCl2", cation: [["Fe", 1]], anion: [["Cl", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeCl3", cation: [["Fe", 1]], anion: [["Cl", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeCr2O7", cation: [["Fe", 1]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeCrO4", cation: [["Fe", 1]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeF2", cation: [["Fe", 1]], anion: [["F", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeF3", cation: [["Fe", 1]], anion: [["F", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeHPO4", cation: [["Fe", 1]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeI2", cation: [["Fe", 1]], anion: [["I", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeI3", cation: [["Fe", 1]], anion: [["I", 3]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeMnO4", cation: [["Fe", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FePO4", cation: [["Fe", 1]], anion: [["PO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeS", cation: [["Fe", 1]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeSO3", cation: [["Fe", 1]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "FeSO4", cation: [["Fe", 1]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "H2CO3", cation: [["H", 2]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "H2Cr2O7", cation: [["H", 2]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "H2CrO4", cation: [["H", 2]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "H2HPO4", cation: [["H", 2]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "H2MnO4", cation: [["H", 2]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "H2S", cation: [["H", 2]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "H2SO3", cation: [["H", 2]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "H2SO4", cation: [["H", 2]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "H3PO4", cation: [["H", 3]], anion: [["PO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HCH3COO", cation: [["H", 1]], anion: [["CH3COO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HCN", cation: [["H", 1]], anion: [["CN", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HCl", cation: [["H", 1]], anion: [["Cl", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HClO", cation: [["H", 1]], anion: [["ClO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HClO2", cation: [["H", 1]], anion: [["ClO2", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HClO3", cation: [["H", 1]], anion: [["ClO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HClO4", cation: [["H", 1]], anion: [["ClO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HF", cation: [["H", 1]], anion: [["F", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HH2PO4", cation: [["H", 1]], anion: [["H2PO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HHCO3", cation: [["H", 1]], anion: [["HCO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HHS", cation: [["H", 1]], anion: [["HS", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HHSO3", cation: [["H", 1]], anion: [["HSO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HHSO4", cation: [["H", 1]], anion: [["HSO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HI", cation: [["H", 1]], anion: [["I", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HIO", cation: [["H", 1]], anion: [["IO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HIO3", cation: [["H", 1]], anion: [["IO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HMnO4", cation: [["H", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HNO3", cation: [["H", 1]], anion: [["NO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HOH", cation: [["H", 1]], anion: [["OH", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(CH3COO)2", cation: [["Hg", 1]], anion: [["CH3COO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(CN)2", cation: [["Hg", 1]], anion: [["CN", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(ClO)2", cation: [["Hg", 1]], anion: [["ClO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(ClO2)2", cation: [["Hg", 1]], anion: [["ClO2", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(ClO3)2", cation: [["Hg", 1]], anion: [["ClO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(ClO4)2", cation: [["Hg", 1]], anion: [["ClO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(H2PO4)2", cation: [["Hg", 1]], anion: [["H2PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(HCO3)2", cation: [["Hg", 1]], anion: [["HCO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(HS)2", cation: [["Hg", 1]], anion: [["HS", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(HSO3)2", cation: [["Hg", 1]], anion: [["HSO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(HSO4)2", cation: [["Hg", 1]], anion: [["HSO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(IO)2", cation: [["Hg", 1]], anion: [["IO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(IO3)2", cation: [["Hg", 1]], anion: [["IO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(MnO4)2", cation: [["Hg", 1]], anion: [["MnO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(NO3)2", cation: [["Hg", 1]], anion: [["NO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg(OH)2", cation: [["Hg", 1]], anion: [["OH", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Hg3(PO4)2", cation: [["Hg", 3]], anion: [["PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HgCO3", cation: [["Hg", 1]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HgCl2", cation: [["Hg", 1]], anion: [["Cl", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HgCr2O7", cation: [["Hg", 1]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HgCrO4", cation: [["Hg", 1]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HgF2", cation: [["Hg", 1]], anion: [["F", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HgHPO4", cation: [["Hg", 1]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HgI2", cation: [["Hg", 1]], anion: [["I", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HgMnO4", cation: [["Hg", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HgS", cation: [["Hg", 1]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HgSO3", cation: [["Hg", 1]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "HgSO4", cation: [["Hg", 1]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "K2CO3", cation: [["K", 2]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "K2Cr2O7", cation: [["K", 2]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "K2CrO4", cation: [["K", 2]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "K2HPO4", cation: [["K", 2]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "K2MnO4", cation: [["K", 2]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "K2S", cation: [["K", 2]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "K2SO3", cation: [["K", 2]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "K2SO4", cation: [["K", 2]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "K3PO4", cation: [["K", 3]], anion: [["PO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KCH3COO", cation: [["K", 1]], anion: [["CH3COO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KCN", cation: [["K", 1]], anion: [["CN", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KCl", cation: [["K", 1]], anion: [["Cl", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KClO", cation: [["K", 1]], anion: [["ClO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KClO2", cation: [["K", 1]], anion: [["ClO2", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KClO3", cation: [["K", 1]], anion: [["ClO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KClO4", cation: [["K", 1]], anion: [["ClO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KF", cation: [["K", 1]], anion: [["F", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KH2PO4", cation: [["K", 1]], anion: [["H2PO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KHCO3", cation: [["K", 1]], anion: [["HCO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KHS", cation: [["K", 1]], anion: [["HS", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KHSO3", cation: [["K", 1]], anion: [["HSO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KHSO4", cation: [["K", 1]], anion: [["HSO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KI", cation: [["K", 1]], anion: [["I", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KIO", cation: [["K", 1]], anion: [["IO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KIO3", cation: [["K", 1]], anion: [["IO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KMnO4", cation: [["K", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KNO3", cation: [["K", 1]], anion: [["NO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "KOH", cation: [["K", 1]], anion: [["OH", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(CH3COO)2", cation: [["Mg", 1]], anion: [["CH3COO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(CN)2", cation: [["Mg", 1]], anion: [["CN", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(ClO)2", cation: [["Mg", 1]], anion: [["ClO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(ClO2)2", cation: [["Mg", 1]], anion: [["ClO2", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(ClO3)2", cation: [["Mg", 1]], anion: [["ClO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(ClO4)2", cation: [["Mg", 1]], anion: [["ClO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(H2PO4)2", cation: [["Mg", 1]], anion: [["H2PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(HCO3)2", cation: [["Mg", 1]], anion: [["HCO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(HS)2", cation: [["Mg", 1]], anion: [["HS", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(HSO3)2", cation: [["Mg", 1]], anion: [["HSO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(HSO4)2", cation: [["Mg", 1]], anion: [["HSO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(IO)2", cation: [["Mg", 1]], anion: [["IO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(IO3)2", cation: [["Mg", 1]], anion: [["IO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(MnO4)2", cation: [["Mg", 1]], anion: [["MnO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(NO3)2", cation: [["Mg", 1]], anion: [["NO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg(OH)2", cation: [["Mg", 1]], anion: [["OH", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mg3(PO4)2", cation: [["Mg", 3]], anion: [["PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MgCO3", cation: [["Mg", 1]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MgCl2", cation: [["Mg", 1]], anion: [["Cl", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MgCr2O7", cation: [["Mg", 1]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MgCrO4", cation: [["Mg", 1]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MgF2", cation: [["Mg", 1]], anion: [["F", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MgHPO4", cation: [["Mg", 1]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MgI2", cation: [["Mg", 1]], anion: [["I", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MgMnO4", cation: [["Mg", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MgS", cation: [["Mg", 1]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MgSO3", cation: [["Mg", 1]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MgSO4", cation: [["Mg", 1]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(CH3COO)2", cation: [["Mn", 1]], anion: [["CH3COO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(CN)2", cation: [["Mn", 1]], anion: [["CN", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(ClO)2", cation: [["Mn", 1]], anion: [["ClO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(ClO2)2", cation: [["Mn", 1]], anion: [["ClO2", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(ClO3)2", cation: [["Mn", 1]], anion: [["ClO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(ClO4)2", cation: [["Mn", 1]], anion: [["ClO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(H2PO4)2", cation: [["Mn", 1]], anion: [["H2PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(HCO3)2", cation: [["Mn", 1]], anion: [["HCO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(HS)2", cation: [["Mn", 1]], anion: [["HS", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(HSO3)2", cation: [["Mn", 1]], anion: [["HSO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(HSO4)2", cation: [["Mn", 1]], anion: [["HSO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(IO)2", cation: [["Mn", 1]], anion: [["IO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(IO3)2", cation: [["Mn", 1]], anion: [["IO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(MnO4)2", cation: [["Mn", 1]], anion: [["MnO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(NO3)2", cation: [["Mn", 1]], anion: [["NO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn(OH)2", cation: [["Mn", 1]], anion: [["OH", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Mn3(PO4)2", cation: [["Mn", 3]], anion: [["PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MnCO3", cation: [["Mn", 1]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MnCl2", cation: [["Mn", 1]], anion: [["Cl", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MnCr2O7", cation: [["Mn", 1]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MnCrO4", cation: [["Mn", 1]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MnF2", cation: [["Mn", 1]], anion: [["F", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MnHPO4", cation: [["Mn", 1]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MnI2", cation: [["Mn", 1]], anion: [["I", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MnMnO4", cation: [["Mn", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MnS", cation: [["Mn", 1]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MnSO3", cation: [["Mn", 1]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "MnSO4", cation: [["Mn", 1]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4CH3COO", cation: [["NH4", 1]], anion: [["CH3COO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4CN", cation: [["NH4", 1]], anion: [["CN", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4Cl", cation: [["NH4", 1]], anion: [["Cl", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4ClO", cation: [["NH4", 1]], anion: [["ClO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4ClO2", cation: [["NH4", 1]], anion: [["ClO2", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4ClO3", cation: [["NH4", 1]], anion: [["ClO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4ClO4", cation: [["NH4", 1]], anion: [["ClO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4F", cation: [["NH4", 1]], anion: [["F", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4H2PO4", cation: [["NH4", 1]], anion: [["H2PO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4HCO3", cation: [["NH4", 1]], anion: [["HCO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4HS", cation: [["NH4", 1]], anion: [["HS", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4HSO3", cation: [["NH4", 1]], anion: [["HSO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4HSO4", cation: [["NH4", 1]], anion: [["HSO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4I", cation: [["NH4", 1]], anion: [["I", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4IO", cation: [["NH4", 1]], anion: [["IO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4IO3", cation: [["NH4", 1]], anion: [["IO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4MnO4", cation: [["NH4", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4NO3", cation: [["NH4", 1]], anion: [["NO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NH4OH", cation: [["NH4", 1]], anion: [["OH", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Na2CO3", cation: [["Na", 2]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Na2Cr2O7", cation: [["Na", 2]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Na2CrO4", cation: [["Na", 2]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Na2HPO4", cation: [["Na", 2]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Na2MnO4", cation: [["Na", 2]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Na2S", cation: [["Na", 2]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Na2SO3", cation: [["Na", 2]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Na2SO4", cation: [["Na", 2]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Na3PO4", cation: [["Na", 3]], anion: [["PO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaCH3COO", cation: [["Na", 1]], anion: [["CH3COO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaCN", cation: [["Na", 1]], anion: [["CN", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaCl", cation: [["Na", 1]], anion: [["Cl", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaClO", cation: [["Na", 1]], anion: [["ClO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaClO2", cation: [["Na", 1]], anion: [["ClO2", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaClO3", cation: [["Na", 1]], anion: [["ClO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaClO4", cation: [["Na", 1]], anion: [["ClO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaF", cation: [["Na", 1]], anion: [["F", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaH2PO4", cation: [["Na", 1]], anion: [["H2PO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaHCO3", cation: [["Na", 1]], anion: [["HCO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaHS", cation: [["Na", 1]], anion: [["HS", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaHSO3", cation: [["Na", 1]], anion: [["HSO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaHSO4", cation: [["Na", 1]], anion: [["HSO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaI", cation: [["Na", 1]], anion: [["I", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaIO", cation: [["Na", 1]], anion: [["IO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaIO3", cation: [["Na", 1]], anion: [["IO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaMnO4", cation: [["Na", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaNO3", cation: [["Na", 1]], anion: [["NO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "NaOH", cation: [["Na", 1]], anion: [["OH", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(CH3COO)2", cation: [["Pb", 1]], anion: [["CH3COO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(CN)2", cation: [["Pb", 1]], anion: [["CN", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(ClO)2", cation: [["Pb", 1]], anion: [["ClO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(ClO2)2", cation: [["Pb", 1]], anion: [["ClO2", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(ClO3)2", cation: [["Pb", 1]], anion: [["ClO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(ClO4)2", cation: [["Pb", 1]], anion: [["ClO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(H2PO4)2", cation: [["Pb", 1]], anion: [["H2PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(HCO3)2", cation: [["Pb", 1]], anion: [["HCO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(HS)2", cation: [["Pb", 1]], anion: [["HS", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(HSO3)2", cation: [["Pb", 1]], anion: [["HSO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(HSO4)2", cation: [["Pb", 1]], anion: [["HSO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(IO)2", cation: [["Pb", 1]], anion: [["IO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(IO3)2", cation: [["Pb", 1]], anion: [["IO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(MnO4)2", cation: [["Pb", 1]], anion: [["MnO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(NO3)2", cation: [["Pb", 1]], anion: [["NO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb(OH)2", cation: [["Pb", 1]], anion: [["OH", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Pb3(PO4)2", cation: [["Pb", 3]], anion: [["PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "PbCO3", cation: [["Pb", 1]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "PbCl2", cation: [["Pb", 1]], anion: [["Cl", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "PbCr2O7", cation: [["Pb", 1]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "PbCrO4", cation: [["Pb", 1]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "PbF2", cation: [["Pb", 1]], anion: [["F", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "PbHPO4", cation: [["Pb", 1]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "PbI2", cation: [["Pb", 1]], anion: [["I", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "PbMnO4", cation: [["Pb", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "PbS", cation: [["Pb", 1]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "PbSO3", cation: [["Pb", 1]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "PbSO4", cation: [["Pb", 1]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Tl2CO3", cation: [["Tl", 2]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Tl2Cr2O7", cation: [["Tl", 2]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Tl2CrO4", cation: [["Tl", 2]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Tl2HPO4", cation: [["Tl", 2]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Tl2MnO4", cation: [["Tl", 2]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Tl2S", cation: [["Tl", 2]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Tl2SO3", cation: [["Tl", 2]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Tl2SO4", cation: [["Tl", 2]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Tl3PO4", cation: [["Tl", 3]], anion: [["PO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlCH3COO", cation: [["Tl", 1]], anion: [["CH3COO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlCN", cation: [["Tl", 1]], anion: [["CN", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlCl", cation: [["Tl", 1]], anion: [["Cl", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlClO", cation: [["Tl", 1]], anion: [["ClO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlClO2", cation: [["Tl", 1]], anion: [["ClO2", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlClO3", cation: [["Tl", 1]], anion: [["ClO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlClO4", cation: [["Tl", 1]], anion: [["ClO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlF", cation: [["Tl", 1]], anion: [["F", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlH2PO4", cation: [["Tl", 1]], anion: [["H2PO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlHCO3", cation: [["Tl", 1]], anion: [["HCO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlHS", cation: [["Tl", 1]], anion: [["HS", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlHSO3", cation: [["Tl", 1]], anion: [["HSO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlHSO4", cation: [["Tl", 1]], anion: [["HSO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlI", cation: [["Tl", 1]], anion: [["I", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlIO", cation: [["Tl", 1]], anion: [["IO", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlIO3", cation: [["Tl", 1]], anion: [["IO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlMnO4", cation: [["Tl", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlNO3", cation: [["Tl", 1]], anion: [["NO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "TlOH", cation: [["Tl", 1]], anion: [["OH", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(CH3COO)2", cation: [["Zn", 1]], anion: [["CH3COO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(CN)2", cation: [["Zn", 1]], anion: [["CN", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(ClO)2", cation: [["Zn", 1]], anion: [["ClO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(ClO2)2", cation: [["Zn", 1]], anion: [["ClO2", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(ClO3)2", cation: [["Zn", 1]], anion: [["ClO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(ClO4)2", cation: [["Zn", 1]], anion: [["ClO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(H2PO4)2", cation: [["Zn", 1]], anion: [["H2PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(HCO3)2", cation: [["Zn", 1]], anion: [["HCO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(HS)2", cation: [["Zn", 1]], anion: [["HS", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(HSO3)2", cation: [["Zn", 1]], anion: [["HSO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(HSO4)2", cation: [["Zn", 1]], anion: [["HSO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(IO)2", cation: [["Zn", 1]], anion: [["IO", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(IO3)2", cation: [["Zn", 1]], anion: [["IO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(MnO4)2", cation: [["Zn", 1]], anion: [["MnO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(NO3)2", cation: [["Zn", 1]], anion: [["NO3", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn(OH)2", cation: [["Zn", 1]], anion: [["OH", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "Zn3(PO4)2", cation: [["Zn", 3]], anion: [["PO4", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "ZnCO3", cation: [["Zn", 1]], anion: [["CO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "ZnCl2", cation: [["Zn", 1]], anion: [["Cl", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "ZnCr2O7", cation: [["Zn", 1]], anion: [["Cr2O7", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "ZnCrO4", cation: [["Zn", 1]], anion: [["CrO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "ZnF2", cation: [["Zn", 1]], anion: [["F", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "ZnHPO4", cation: [["Zn", 1]], anion: [["HPO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "ZnI2", cation: [["Zn", 1]], anion: [["I", 2]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "ZnMnO4", cation: [["Zn", 1]], anion: [["MnO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "ZnS", cation: [["Zn", 1]], anion: [["S", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "ZnSO3", cation: [["Zn", 1]], anion: [["SO3", 1]], mfH: undefined, mfS: undefined, mfG: undefined},
//     {name: "ZnSO4", cation: [["Zn", 1]], anion: [["SO4", 1]], mfH: undefined, mfS: undefined, mfG: undefined}
// ];
// var simple = {
//     H2O : {cation: undefined, anion: undefined, mfG: -228.588656},
//     CO2 : {cation: undefined, anion: undefined, mfG: -394.38384},
//     CO  : {cation: undefined, anion: undefined, mfG: -137.27704},
//     COCl: {cation: undefined, anion: undefined, mfG: -206.77328},
//     H2  : {cation: undefined, anion: undefined, mfG: 0},
//     Cl2 : {cation: undefined, anion: undefined, mfG: 0},
//     O2  : {cation: undefined, anion: undefined, mfG: 0},
//     P4  : {cation: undefined, anion: undefined, mfG: 72.3832},
//     P   : {cation: undefined, anion: undefined, mfG: 0},
//     K   : {cation: undefined, anion: undefined, mfG: 0},
//     Na  : {cation: undefined, anion: undefined, mfG: 0},
//     Fe  : {cation: undefined, anion: undefined, mfG: 0},
//     Ca  : {cation: undefined, anion: undefined, mfG: 0},
//     Mg  : {cation: undefined, anion: undefined, mfG: 0},
//     Zn  : {cation: undefined, anion: undefined, mfG: 0},
//     Cu  : {cation: undefined, anion: undefined, mfG: 0},
//     Pb  : {cation: undefined, anion: undefined, mfG: 0},
//     Ba  : {cation: undefined, anion: undefined, mfG: 0},
//     Hg  : {cation: undefined, anion: undefined, mfG: 0},
//     Cd  : {cation: undefined, anion: undefined, mfG: 0},
//     Tl  : {cation: undefined, anion: undefined, mfG: 0},
// };